use std::path::Path;

use tauri::{AppHandle, Emitter, Manager, State};

use crate::db;
use crate::domain::{AgentTask, DiffStats, FileDiff, TaskStatus};
use crate::state::AppState;

fn now() -> String {
    chrono::Utc::now().to_rfc3339()
}

fn build_commit_message(task: &AgentTask, summary: Option<&str>) -> String {
    let subject = format!("{}: {}", task.jira_issue_key, task.title);
    match summary.map(str::trim).filter(|value| !value.is_empty()) {
        Some(summary) => format!(
            "{subject}\n\n{summary}\n\nGenerated by JIRA Agent for {}.",
            task.jira_issue_key
        ),
        None => subject,
    }
}

pub fn start_commit(app: AppHandle, task_id: String) {
    std::thread::spawn(move || {
        if let Err(error) = commit_task(&app, &task_id, None) {
            fail_commit(&app, &task_id, &error);
        }
    });
}

fn commit_task(app: &AppHandle, task_id: &str, message: Option<String>) -> Result<String, String> {
    let state = app
        .try_state::<AppState>()
        .ok_or_else(|| "state unavailable".to_string())?;

    let (task, summary) = {
        let connection = state.db.lock().map_err(|error| error.to_string())?;
        let task = db::get_task(&connection, task_id)?
            .ok_or_else(|| format!("task not found: {task_id}"))?;
        let summary = match task.approved_plan_version.or(task.plan_version) {
            Some(version) => db::get_plan_version(&connection, task_id, version)?
                .map(|version| version.content.summary),
            None => None,
        };
        (task, summary)
    };

    match task.status {
        TaskStatus::Committing => {}
        TaskStatus::Failed => {
            let connection = state.db.lock().map_err(|error| error.to_string())?;
            db::update_task_status(&connection, task_id, TaskStatus::Committing, &now())?;
        }
        other => {
            return Err(format!(
                "task {task_id} cannot be committed from status {other:?}"
            ))
        }
    }

    let workspace_path = task
        .workspace_path
        .clone()
        .ok_or_else(|| "task has no workspace".to_string())?;
    let path = Path::new(&workspace_path);
    if !path.is_dir() {
        return Err(format!("workspace path does not exist: {workspace_path}"));
    }

    let commit_message = message
        .filter(|value| !value.trim().is_empty())
        .unwrap_or_else(|| build_commit_message(&task, summary.as_deref()));

    // Phase 26: measure the change before it is committed (afterwards the
    // working tree diff is empty).
    if let Ok(stats) = crate::git::worktree_stats(path) {
        crate::metrics::record(
            app,
            "files.changed",
            stats.files_changed as f64,
            Some(task_id),
            serde_json::json!({ "additions": stats.additions, "deletions": stats.deletions }),
        );
    }

    let hash = crate::git::commit_all(path, &commit_message)?;

    {
        let connection = state.db.lock().map_err(|error| error.to_string())?;
        db::set_task_commit(&connection, task_id, &hash, &now())?;
        db::update_task_status(&connection, task_id, TaskStatus::PrCreating, &now())?;
    }
    crate::commands::cloud_socket::emit_task_updated(app, &state, task_id);
    let _ = app.emit(
        "commit://created",
        serde_json::json!({ "taskId": task_id, "commitHash": hash }),
    );
    crate::commands::github::start_publish(app.clone(), task_id.to_string());

    Ok(hash)
}

fn fail_commit(app: &AppHandle, task_id: &str, error: &str) {
    crate::logging::error(
        "commit",
        "commit failed",
        serde_json::json!({ "taskId": task_id, "error": error }),
    );
    if let Some(state) = app.try_state::<AppState>() {
        if let Ok(connection) = state.db.lock() {
            let _ = db::update_task_status(&connection, task_id, TaskStatus::Failed, &now());
        }
        crate::commands::cloud_socket::emit_task_updated(app, &state, task_id);
    }
    let _ = app.emit(
        "commit://error",
        serde_json::json!({ "taskId": task_id, "error": error }),
    );
}

#[tauri::command]
pub fn commit_changes(
    app: AppHandle,
    task_id: String,
    message: Option<String>,
) -> Result<String, String> {
    commit_task(&app, &task_id, message)
}

#[tauri::command]
pub fn get_workspace_stats(state: State<AppState>, task_id: String) -> Result<DiffStats, String> {
    let workspace_path = {
        let connection = state.db.lock().map_err(|error| error.to_string())?;
        let task = db::get_task(&connection, &task_id)?
            .ok_or_else(|| format!("task not found: {task_id}"))?;
        task.workspace_path
            .ok_or_else(|| "task has no workspace yet".to_string())?
    };

    let path = Path::new(&workspace_path);
    if !path.is_dir() {
        return Err(format!("workspace path does not exist: {workspace_path}"));
    }

    crate::git::worktree_stats(path)
}

#[tauri::command]
pub fn get_workspace_diffs(
    state: State<AppState>,
    task_id: String,
) -> Result<Vec<FileDiff>, String> {
    let workspace_path = {
        let connection = state.db.lock().map_err(|error| error.to_string())?;
        let task = db::get_task(&connection, &task_id)?
            .ok_or_else(|| format!("task not found: {task_id}"))?;
        task.workspace_path
            .ok_or_else(|| "task has no workspace yet".to_string())?
    };

    let path = Path::new(&workspace_path);
    if !path.is_dir() {
        return Err(format!("workspace path does not exist: {workspace_path}"));
    }

    let stats = crate::git::worktree_stats(path)?;
    Ok(stats
        .files
        .iter()
        .map(|file| crate::git::file_diff(path, &file.path))
        .collect())
}
