use std::path::Path;

use tauri::{AppHandle, Emitter, Manager, State};
use uuid::Uuid;

use crate::db;
use crate::domain::{AgentTask, PlanContent, PullRequest, TaskStatus};
use crate::github::{self, GithubClient};
use crate::state::AppState;

fn now() -> String {
    chrono::Utc::now().to_rfc3339()
}

fn github_token(state: &AppState) -> Result<String, String> {
    crate::secrets::get(state, "githubToken")?
        .filter(|token| !token.trim().is_empty())
        .ok_or_else(|| "GitHub token is not configured".to_string())
}

fn emit_task(app: &AppHandle, state: &AppState, task_id: &str) {
    crate::commands::cloud_socket::emit_task_updated(app, state, task_id);
}

fn build_pr_body(task: &AgentTask, plan: Option<&PlanContent>) -> String {
    match plan {
        Some(plan) => {
            let changes = plan
                .steps
                .iter()
                .map(|step| format!("- {}", step.description))
                .collect::<Vec<_>>()
                .join("\n");
            let tests = if plan.tests.is_empty() {
                "- (run in CI)".to_string()
            } else {
                plan.tests
                    .iter()
                    .map(|test| format!("- {test}"))
                    .collect::<Vec<_>>()
                    .join("\n")
            };
            format!(
                "JIRA: {key}\n\n## Summary\n{summary}\n\n## Changes\n{changes}\n\n## Tests\n{tests}\n\nGenerated by JIRA Agent.",
                key = task.jira_issue_key,
                summary = plan.summary,
                changes = changes,
                tests = tests,
            )
        }
        None => format!(
            "JIRA: {}\n\nGenerated by JIRA Agent.",
            task.jira_issue_key
        ),
    }
}

pub fn start_publish(app: AppHandle, task_id: String) {
    std::thread::spawn(move || {
        if let Err(error) = publish_task(&app, &task_id, None, None) {
            fail(&app, &task_id, &error);
        }
    });
}

fn publish_task(
    app: &AppHandle,
    task_id: &str,
    title: Option<String>,
    body: Option<String>,
) -> Result<(), String> {
    let state = app
        .try_state::<AppState>()
        .ok_or_else(|| "state unavailable".to_string())?;

    let (task, repository, plan) = {
        let connection = state.db.lock().map_err(|error| error.to_string())?;
        let task = db::get_task(&connection, task_id)?
            .ok_or_else(|| format!("task not found: {task_id}"))?;
        let repository = db::get_repository(&connection, &task.repository_id)?
            .ok_or_else(|| format!("repository not found: {}", task.repository_id))?;
        let plan = match task.approved_plan_version.or(task.plan_version) {
            Some(version) => db::get_plan_version(&connection, task_id, version)?
                .map(|version| version.content),
            None => None,
        };
        (task, repository, plan)
    };

    match task.status {
        TaskStatus::PrCreating => {}
        TaskStatus::Failed => {
            let connection = state.db.lock().map_err(|error| error.to_string())?;
            db::update_task_status(&connection, task_id, TaskStatus::PrCreating, &now())?;
        }
        other => {
            return Err(format!(
                "task {task_id} cannot publish a pull request from status {other:?}"
            ))
        }
    }

    if let Ok(connection) = state.db.lock() {
        if let Ok(Some(existing)) = db::get_pull_request(&connection, task_id) {
            let _ = app.emit("pr://created", &existing);
            return Ok(());
        }
    }

    let workspace = task
        .workspace_path
        .clone()
        .ok_or_else(|| "task has no workspace".to_string())?;
    let branch = task
        .branch_name
        .clone()
        .ok_or_else(|| "task has no branch".to_string())?;
    let (owner, repo) = github::parse_owner_repo(&repository.remote_url)
        .ok_or_else(|| "remote origin is not a GitHub repository".to_string())?;
    let base = repository.default_branch.clone();
    let token = github_token(&state)?;

    crate::git::push_branch(Path::new(&workspace), &branch)?;

    let pr_title = title
        .filter(|value| !value.trim().is_empty())
        .unwrap_or_else(|| format!("{}: {}", task.jira_issue_key, task.title));
    let pr_body = body
        .filter(|value| !value.trim().is_empty())
        .unwrap_or_else(|| build_pr_body(&task, plan.as_ref()));

    let value = crate::opencode::run_blocking({
        let token = token.clone();
        let owner = owner.clone();
        let repo = repo.clone();
        let pr_title = pr_title.clone();
        let branch = branch.clone();
        let base = base.clone();
        let pr_body = pr_body.clone();
        move || {
            GithubClient::new(token)?.create_pull_request(
                &owner, &repo, &pr_title, &branch, &base, &pr_body,
            )
        }
    })?;

    let number = value
        .get("number")
        .and_then(|value| value.as_u64())
        .unwrap_or(0) as u32;
    let url = value
        .get("html_url")
        .and_then(|value| value.as_str())
        .unwrap_or("")
        .to_string();

    let pull_request = PullRequest {
        id: Uuid::new_v4().to_string(),
        task_id: task_id.to_string(),
        provider: "github".to_string(),
        number,
        url,
        branch,
        base_branch: base,
        status: "open".to_string(),
        created_at: now(),
    };

    {
        let connection = state.db.lock().map_err(|error| error.to_string())?;
        db::insert_pull_request(&connection, &pull_request)?;
        db::update_task_status(&connection, task_id, TaskStatus::PrCreated, &now())?;
    }
    emit_task(app, &state, task_id);
    let _ = app.emit("pr://created", &pull_request);
    crate::logging::info(
        "github",
        "pull request created",
        serde_json::json!({
            "taskId": task_id,
            "number": pull_request.number,
            "url": pull_request.url,
        }),
    );

    if crate::commands::jira::is_connected(&state) {
        if let Err(error) = crate::commands::jira::sync_task(app, task_id) {
            let _ = app.emit(
                "jira://error",
                serde_json::json!({ "taskId": task_id, "error": error }),
            );
        }
    }

    Ok(())
}

fn fail(app: &AppHandle, task_id: &str, error: &str) {
    let detail = crate::metrics::truncate(error, 500);
    crate::logging::error(
        "github",
        "pull request creation failed",
        serde_json::json!({ "taskId": task_id, "error": detail }),
    );
    crate::metrics::record(
        app,
        "pr.create_failed",
        1.0,
        Some(task_id),
        serde_json::json!({ "error": detail }),
    );
    if let Some(state) = app.try_state::<AppState>() {
        if let Ok(connection) = state.db.lock() {
            let _ = db::update_task_status(&connection, task_id, TaskStatus::Failed, &now());
        }
        emit_task(app, &state, task_id);
    }
    let _ = app.emit(
        "pr://error",
        serde_json::json!({ "taskId": task_id, "error": error }),
    );
}

#[tauri::command]
pub fn set_github_token(state: State<AppState>, token: Option<String>) -> Result<(), String> {
    match token.filter(|value| !value.trim().is_empty()) {
        Some(token) => crate::secrets::set(&state, "githubToken", &token),
        None => crate::secrets::delete(&state, "githubToken"),
    }
}

#[tauri::command]
pub fn get_github_account(state: State<AppState>) -> Result<Option<String>, String> {
    let token = crate::secrets::get(&state, "githubToken")?;
    match token.filter(|value| !value.trim().is_empty()) {
        Some(token) => {
            crate::opencode::run_blocking(move || GithubClient::new(token)?.account()).map(Some)
        }
        None => Ok(None),
    }
}

#[tauri::command]
pub fn push_branch(app: AppHandle, task_id: String) -> Result<(), String> {
    let state = app
        .try_state::<AppState>()
        .ok_or_else(|| "state unavailable".to_string())?;
    let (workspace, branch) = {
        let connection = state.db.lock().map_err(|error| error.to_string())?;
        let task = db::get_task(&connection, &task_id)?
            .ok_or_else(|| format!("task not found: {task_id}"))?;
        (
            task.workspace_path
                .ok_or_else(|| "task has no workspace".to_string())?,
            task.branch_name
                .ok_or_else(|| "task has no branch".to_string())?,
        )
    };
    crate::git::push_branch(Path::new(&workspace), &branch)
}

#[tauri::command]
pub fn create_pull_request(
    app: AppHandle,
    task_id: String,
    title: Option<String>,
    body: Option<String>,
) -> Result<(), String> {
    match publish_task(&app, &task_id, title, body) {
        Ok(()) => Ok(()),
        Err(error) => {
            let detail = crate::metrics::truncate(&error, 500);
            crate::logging::error(
                "github",
                "pull request creation failed",
                serde_json::json!({ "taskId": task_id, "error": detail }),
            );
            crate::metrics::record(
                &app,
                "pr.create_failed",
                1.0,
                Some(&task_id),
                serde_json::json!({ "error": detail }),
            );
            Err(error)
        }
    }
}

#[tauri::command]
pub fn get_pull_request(
    state: State<AppState>,
    task_id: String,
) -> Result<Option<PullRequest>, String> {
    let connection = state.db.lock().map_err(|error| error.to_string())?;
    db::get_pull_request(&connection, &task_id)
}
